// Mapeo de códigos de idioma ISO 639-1 a nombres completos en español
export const LANGUAGE_MAP = {
  'en': 'Inglés',
  'eng': 'Inglés',
  'es': 'Español',
  'spa': 'Español',
  'fr': 'Francés',
  'fra': 'Francés',
  'de': 'Alemán',
  'deu': 'Alemán',
  'it': 'Italiano',
  'ita': 'Italiano',
  'pt': 'Portugués',
  'por': 'Portugués',
  'ru': 'Ruso',
  'rus': 'Ruso',
  'ja': 'Japonés',
  'jpn': 'Japonés',
  'chi': 'Chino',
  'zh': 'Chino',
  'zho': 'Chino',
  'zh-CN': 'Chino Simplificado',
  'zh-TW': 'Chino Tradicional',
  'ko': 'Coreano',
  'kor': 'Coreano',
  'ar': 'Árabe',
  'ara': 'Árabe',
  'he': 'Hebreo',
  'heb': 'Hebreo',
  'hi': 'Hindi',
  'hin': 'Hindi',
  'nl': 'Neerlandés',
  'nld': 'Neerlandés',
  'pl': 'Polaco',
  'pol': 'Polaco',
  'tr': 'Turco',
  'tur': 'Turco',
  'vi': 'Vietnamita',
  'vie': 'Vietnamita',
  'th': 'Tailandés',
  'tha': 'Tailandés',
  'sv': 'Sueco',
  'swe': 'Sueco',
  'no': 'Noruego',
  'nor': 'Noruego',
  'da': 'Danés',
  'dan': 'Danés',
  'fi': 'Finlandés',
  'fin': 'Finlandés',
  'el': 'Griego',
  'ell': 'Griego',
  'cs': 'Checo',
  'ces': 'Checo',
  'hu': 'Húngaro',
  'hun': 'Húngaro',
  'ro': 'Rumano',
  'ron': 'Rumano',
  'uk': 'Ucraniano',
  'ukr': 'Ucraniano',
  'id': 'Indonesio',
  'ind': 'Indonesio',
  'ms': 'Malayo',
  'msa': 'Malayo',
  'tl': 'Tagalo',
  'tgl': 'Tagalo',
  'fil': 'Filipino',
  'bn': 'Bengali',
  'ben': 'Bengali',
  'pa': 'Punjabi',
  'pan': 'Punjabi',
  'fa': 'Persa',
  'fas': 'Persa',
  'ur': 'Urdu',
  'urd': 'Urdu',
  'sw': 'Suajili',
  'swa': 'Suajili',
};

/**
 * Convierte un código de idioma a su nombre completo en español
 * @param {string} code - Código de idioma (ej: 'eng', 'en', 'spa')
 * @returns {string} - Nombre del idioma en español o el código original si no se encuentra
 */
export function getLanguageName(code) {
  if (!code) return 'Desconocido';
  const name = LANGUAGE_MAP[code.toLowerCase()];
  return name || code;
}
